<?php
$polIDPK=trim($_POST['polIDPK']);
$polOrgIDFK=trim($_POST['polOrgIDFK']);
$polStatusIDFK=trim($_POST['polStatusIDFK']);
$polMaspolNum=trim($_POST['polMaspolNum']);
$polQuoNum=trim($_POST['polQuoNum']);
$polNum=trim($_POST['polNum']);
$polCat=trim($_POST['polCat']);
$polReFlag=trim($_POST['polReFlag']);
$polEffDate=trim($_POST['polEffDate']);
$polExpDate=trim($_POST['polExpDate']);
$polQuoCreateDate=trim($_POST['polQuoCreateDate']);
$polQuoDate=trim($_POST['polQuoDate']);
$polProDate=trim($_POST['polProDate']);
$polAppReceivedDate=trim($_POST['polAppReceivedDate']);
$polIssueDate=trim($_POST['polIssueDate']);
$polIssueBy=trim($_POST['polIssueBy']);
$polAGTIDFK=trim($_POST['polAGTIDFK']);
$polPRODIDFK=trim($_POST['polPRODIDFK']);
$polPREMIDFK=trim($_POST['polPREMIDFK']);
$polCUSIDFKPHD=trim($_POST['polCUSIDFKPHD']);
$polCUSAddrIDPHD=trim($_POST['polCUSAddrIDPHD']);
$polCUSIDFKINS=trim($_POST['polCUSIDFKINS']);
$polCUSAddrIDINS=trim($_POST['polCUSAddrIDINS']);
$polVEHIDFK=trim($_POST['polVEHIDFK']);
$polUpdatedDate=trim($_POST['polUpdatedDate']);
$polUpdatedBy=trim($_POST['polUpdatedBy']);

$orgIDPK=trim($_POST['orgIDPK']);
$staIDPK=trim($_POST['staIDPK']);
$redKey=trim($_POST['redKey']);

$vehIDPK="";
$vehTARIDFK=trim($_POST['vehTARIDFK']);
$vehTARvehCodeFK=trim($_POST['vehTARvehCodeFK']);
$vehREDKEYFK=trim($_POST['vehREDKEYFK']);
$vehLicenseNum=trim($_POST['vehLicenseNum']);
$vehChassisNum=trim($_POST['vehChassisNum']);
$vehCapacity=trim($_POST['vehCapacity']);
$vehSeat=trim($_POST['vehSeat']);
$vehWeight=trim($_POST['vehWeight']);
$vehEngineNum="";
$vehNewCar="";
$vehDriveArea="";
$vehProvIDFK="";
$vehColor="";
$vehCountry="";
$vehQuoNumRef="";
$vehUpdatedDate="";
$vehUpdatedBy="";

$premIDPK=trim($_POST['premIDPK']);
$premStdNet=trim($_POST['premStdNet']);
$premStdVat=trim($_POST['premStdVat']);
$premStdStampDuty=trim($_POST['premStdStampDuty']);
$premStdTotal=trim($_POST['premStdTotal']);
$premPercentVat=trim($_POST['premPercentVat']);
$premPerDiscount=trim($_POST['premPerDiscount']);
$premDiscountFlag=trim($_POST['premDiscountFlag']);
$premDiscount=trim($_POST['premDiscount']);
$premNet=trim($_POST['premNet']);
$premStampDuty=trim($_POST['premStampDuty']);
$premVat=trim($_POST['premVat']);
$premTotal=trim($_POST['premTotal']);
$premQuoNumRef=trim($_POST['premQuoNumRef']);
$premOutstanding=trim($_POST['premOutstanding']);
$premPaid=trim($_POST['premPaid']);
$premPaidStatus=trim($_POST['premPaidStatus']);
$premPaidStatusAprv=trim($_POST['premPaidStatusAprv']);
$premPaidBalance=trim($_POST['premPaidBalance']);
$premPaidDate=trim($_POST['premPaidDate']);
$premUpdatedDate=trim($_POST['premUpdatedDate']);
$premUpdatedBy=trim($_POST['premUpdatedBy']);

$PHD_perIDPK=trim($_POST['PHD_perIDPK']);
$PHD_perSalu=trim($_POST['PHD_perSalu']);
$PHD_perFName=trim($_POST['PHD_perFName']);
$PHD_perMName=trim($_POST['PHD_perMName']);
$PHD_perLName=trim($_POST['PHD_perLName']);
$PHD_perDOB=trim($_POST['PHD_perDOB']);
$PHD_perCardType=trim($_POST['PHD_perCardType']);
$PHD_perCardNo=trim($_POST['PHD_perCardNo']);
$PHD_perExpDate=trim($_POST['PHD_perExpDate']);
$PHD_perUpdatedDate=trim($_POST['PHD_perUpdatedDate']);
$PHD_perUpdatedBy=trim($_POST['PHD_perUpdatedBy']);
$PHD_addrIDPK=trim($_POST['PHD_addrIDPK']);
$PHD_addrLine1=trim($_POST['PHD_addrLine1']);
$PHD_addrLine2=trim($_POST['PHD_addrLine2']);
$PHD_addrSubDist=trim($_POST['PHD_addrSubDist']);
$PHD_addrDist=trim($_POST['PHD_addrDist']);
$PHD_addrProv=trim($_POST['PHD_addrProv']);
$PHD_addrZipCode=trim($_POST['PHD_addrZipCode']);
$PHD_addrGeo=trim($_POST['PHD_addrGeo']);
$PHD_addrEmail=trim($_POST['PHD_addrEmail']);
$PHD_addrContType1=trim($_POST['PHD_addrContType1']);
$PHD_addrContNum1=trim($_POST['PHD_addrContNum1']);
$PHD_addrContType2=trim($_POST['PHD_addrContType2']);
$PHD_addrContNum2=trim($_POST['PHD_addrContNum2']);
$PHD_addrUpdatedDate=trim($_POST['PHD_addrUpdatedDate']);
$PHD_addrUpdatedBy=trim($_POST['PHD_addrUpdatedBy']);

echo "polIDPK:".$polIDPK."<br>";
echo "polOrgIDFK:".$polOrgIDFK."<br>";
echo "polStatusIDFK:".$polStatusIDFK."<br>";
echo "polMaspolNum:".$polMaspolNum."<br>";
echo "polQuoNum:".$polQuoNum."<br>";
echo "polNum:".$polNum."<br>";
echo "polCat:".$polCat."<br>";
echo "polReFlag:".$polReFlag."<br>";
echo "polEffDate:".$polEffDate."<br>";
echo "polExpDate:".$polExpDate."<br>";
echo "polQuoCreateDate:".$polQuoCreateDate."<br>";
echo "polQuoDate:".$polQuoDate."<br>";
echo "polProDate:".$polProDate."<br>";
echo "polAppReceivedDate:".$polAppReceivedDate."<br>";
echo "polIssueDate:".$polIssueDate."<br>";
echo "polIssueBy:".$polIssueBy."<br>";
echo "polAGTIDFK:".$polAGTIDFK."<br>";
echo "polPRODIDFK:".$polPRODIDFK."<br>";
echo "polPREMIDFK:".$polPREMIDFK."<br>";
echo "polCUSIDFKPHD:".$polCUSIDFKPHD."<br>";
echo "polCUSAddrIDPHD:".$polCUSAddrIDPHD."<br>";
echo "polCUSIDFKINS:".$polCUSIDFKINS."<br>";
echo "polCUSAddrIDINS:".$polCUSAddrIDINS."<br>";
echo "polVEHIDFK:".$polVEHIDFK."<br>";
echo "polUpdatedDate:".$polUpdatedDate."<br>";
echo "polUpdatedBy:".$polUpdatedBy."<br>";

echo "orgIDPK:".$orgIDPK."<br>";
echo "staIDPK:".$staIDPK."<br>";
echo "redKey:".$redKey."<br>";

echo "vehIDPK:".$vehIDPK."<br>";
echo "vehTARIDFK:".$vehTARIDFK."<br>";
echo "vehTARvehCodeFK:".$vehTARvehCodeFK."<br>";
echo "vehREDKEYFK:".$vehREDKEYFK."<br>";
echo "vehLicenseNum:".$vehLicenseNum."<br>";
echo "vehChassisNum:".$vehChassisNum."<br>";
echo "vehCapacity:".$vehCapacity."<br>";
echo "vehSeat:".$vehSeat."<br>";
echo "vehWeight:".$vehWeight."<br>";
echo "vehEngineNum:".$vehEngineNum."<br>";
echo "vehNewCar:".$vehNewCar."<br>";
echo "vehDriveArea:".$vehDriveArea."<br>";
echo "vehProvIDFK:".$vehProvIDFK."<br>";
echo "vehColor:".$vehColor."<br>";
echo "vehCountry:".$vehCountry."<br>";
echo "vehQuoNumRef:".$vehQuoNumRef."<br>";
echo "vehUpdatedDate:".$vehUpdatedDate."<br>";
echo "vehUpdatedBy:".$vehUpdatedBy."<br>";

echo "premIDPK:".$premIDPK."<br>";
echo "premStdNet:".$premStdNet."<br>";
echo "premStdVat:".$premStdVat."<br>";
echo "premStdStampDuty:".$premStdStampDuty."<br>";
echo "premStdTotal:".$premStdTotal."<br>";
echo "premPercentVat:".$premPercentVat."<br>";
echo "premPerDiscount:".$premPerDiscount."<br>";
echo "premDiscountFlag:".$premDiscountFlag."<br>";
echo "premDiscount:".$premDiscount."<br>";
echo "premNet:".$premNet."<br>";
echo "premStampDuty:".$premStampDuty."<br>";
echo "premVat:".$premVat."<br>";
echo "premTotal:".$premTotal."<br>";
echo "premQuoNumRef:".$premQuoNumRef."<br>";
echo "premOutstanding:".$premOutstanding."<br>";
echo "premPaid:".$premPaid."<br>";
echo "premPaidStatus:".$premPaidStatus."<br>";
echo "premPaidStatusAprv:".$premPaidStatusAprv."<br>";
echo "premPaidBalance:".$premPaidBalance."<br>";
echo "premPaidDate:".$premPaidDate."<br>";
echo "premUpdatedDate:".$premUpdatedDate."<br>";
echo "premUpdatedBy:".$premUpdatedBy."<br>";

echo "PHD_perIDPK:".$PHD_perIDPK."<br>";
echo "PHD_perSalu:".$PHD_perSalu."<br>";
echo "PHD_perFName:".$PHD_perFName."<br>";
echo "PHD_perMName:".$PHD_perMName."<br>";
echo "PHD_perLName:".$PHD_perLName."<br>";
echo "PHD_perDOB:".$PHD_perDOB."<br>";
echo "PHD_perCardType:".$PHD_perCardType."<br>";
echo "PHD_perCardNo:".$PHD_perCardNo."<br>";
echo "PHD_perExpDate:".$PHD_perExpDate."<br>";
echo "PHD_perUpdatedDate:".$PHD_perUpdatedDate."<br>";
echo "PHD_perUpdatedBy:".$PHD_perUpdatedBy."<br>";
echo "PHD_addrIDPK:".$PHD_addrIDPK."<br>";
echo "PHD_addrLine1:".$PHD_addrLine1."<br>";
echo "PHD_addrLine2:".$PHD_addrLine2."<br>";
echo "PHD_addrSubDist:".$PHD_addrSubDist."<br>";
echo "PHD_addrDist:".$PHD_addrDist."<br>";
echo "PHD_addrProv:".$PHD_addrProv."<br>";
echo "PHD_addrZipCode:".$PHD_addrZipCode."<br>";
echo "PHD_addrGeo:".$PHD_addrGeo."<br>";
echo "PHD_addrEmail:".$PHD_addrEmail."<br>";
echo "PHD_addrContType1:".$PHD_addrContType1."<br>";
echo "PHD_addrContNum1:".$PHD_addrContNum1."<br>";
echo "PHD_addrContType2:".$PHD_addrContType2."<br>";
echo "PHD_addrContNum2:".$PHD_addrContNum2."<br>";
echo "PHD_addrUpdatedDate:".$PHD_addrUpdatedDate."<br>";
echo "PHD_addrUpdatedBy:".$PHD_addrUpdatedBy."<br>";
?>