<?php
$polIDPK=trim($_POST['polIDPK']);
$polOrgIDFK=trim($_POST['polOrgIDFK']);
$polStatusIDFK=trim($_POST['polStatusIDFK']);
$polMaspolNum=trim($_POST['polMaspolNum']);
$polQuoNum=trim($_POST['polQuoNum']);
$polNum=trim($_POST['polNum']);
$polCat=trim($_POST['polCat']);
$polReFlag=trim($_POST['polReFlag']);
$polEffDate=trim($_POST['polEffDate']);
$polExpDate=trim($_POST['polExpDate']);
$polQuoCreateDate=trim($_POST['polQuoCreateDate']);
$polQuoDate=trim($_POST['polQuoDate']);
$polProDate=trim($_POST['polProDate']);
$polAppReceivedDate=trim($_POST['polAppReceivedDate']);
$polIssueDate=trim($_POST['polIssueDate']);
$polIssueBy=trim($_POST['polIssueBy']);
$polAGTIDFK=trim($_POST['polAGTIDFK']);
$polPRODIDFK=trim($_POST['polPRODIDFK']);
$polPREMIDFK=trim($_POST['polPREMIDFK']);
$polCUSIDFKPHD=trim($_POST['polCUSIDFKPHD']);
$polCUSAddrIDPHD=trim($_POST['polCUSAddrIDPHD']);
$polCUSIDFKINS=trim($_POST['polCUSIDFKINS']);
$polCUSAddrIDINS=trim($_POST['polCUSAddrIDINS']);
$polVEHIDFK=trim($_POST['polVEHIDFK']);
$polUpdatedDate=trim($_POST['polUpdatedDate']);
$polUpdatedBy=trim($_POST['polUpdatedBy']);

$orgIDPK=trim($_POST['orgIDPK']);
$staIDPK=trim($_POST['staIDPK']);
$redKey=trim($_POST['redKey']);

echo "polIDPK:".$polIDPK."<br>";
echo "polOrgIDFK:".$polOrgIDFK."<br>";
echo "polStatusIDFK:".$polStatusIDFK."<br>";
echo "polMaspolNum:".$polMaspolNum."<br>";
echo "polQuoNum:".$polQuoNum."<br>";
echo "polNum:".$polNum."<br>";
echo "polCat:".$polCat."<br>";
echo "polReFlag:".$polReFlag."<br>";
echo "polEffDate:".$polEffDate."<br>";
echo "polExpDate:".$polExpDate."<br>";
echo "polQuoCreateDate:".$polQuoCreateDate."<br>";
echo "polQuoDate:".$polQuoDate."<br>";
echo "polProDate:".$polProDate."<br>";
echo "polAppReceivedDate:".$polAppReceivedDate."<br>";
echo "polIssueDate:".$polIssueDate."<br>";
echo "polIssueBy:".$polIssueBy."<br>";
echo "polAGTIDFK:".$polAGTIDFK."<br>";
echo "polPRODIDFK:".$polPRODIDFK."<br>";
echo "polPREMIDFK:".$polPREMIDFK."<br>";
echo "polCUSIDFKPHD:".$polCUSIDFKPHD."<br>";
echo "polCUSAddrIDPHD:".$polCUSAddrIDPHD."<br>";
echo "polCUSIDFKINS:".$polCUSIDFKINS."<br>";
echo "polCUSAddrIDINS:".$polCUSAddrIDINS."<br>";
echo "polVEHIDFK:".$polVEHIDFK."<br>";
echo "polUpdatedDate:".$polUpdatedDate."<br>";
echo "polUpdatedBy:".$polUpdatedBy."<br>";

echo "orgIDPK:".$orgIDPK."<br>";
echo "staIDPK:".$staIDPK."<br>";
echo "redKey:".$redKey."<br>";
?>